modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "All Rights Reserved"
[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "Nature's Delight"
updateJSONURL = "https://api.modrinth.com/updates/18s8zHvJ/forge_updates.json"
logoFile="assets/natures_delight/icon.gif"
authors = "Team Hibiscus"
description = '''Farmer's Delight x Nature's Spirit'''

[[mixins]]
config="natures_delight.mixins.json"

[[dependencies."${mod_id}"]]
modId = "neoforge"
mandatory = true
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"
[[dependencies."${mod_id}"]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"


[[dependencies."${mod_id}"]]
modId = "terrablender"
mandatory = true
versionRange = "[1,)"
ordering = "NONE"
side = "BOTH"
[[dependencies."${mod_id}"]]
modId = "farmersdelight"
mandatory = true
versionRange = "[1,)"
ordering = "AFTER"
side = "BOTH"
[[dependencies."${mod_id}"]]
modId = "natures_spirit"
mandatory = true
versionRange = "[1,)"
ordering = "AFTER"
side = "BOTH"